name: PythonTests

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Run setup.py
      run: python setup.py install
    
    - name: Download additional dependencies
      run: ./setup.sh
    
    - name: Run build
      run: python setup.py build

    - name: Test
      run: python -m unittest
